# throw in a robot 
PickerRobot( pose [ -8.7 -37 0.000 0.000 ] name "pickerRobot" color "pink" )
MattsRobot( pose [ 16 -30 0.000 90.000 ] name "carrierRobot" color "cyan")
AnimalRobot( pose [ -15 40.000 0.000 90.000 ] name "animal" color "yellow") 
PersonRobot( pose [ -17 37.000 0.000 0.000 ] name "person" color "red" )

CarrierRobot( pose [ 15 -20 0.000 90.000 ] name "carrierRobot" color "cyan")
TractorRobot( pose [ -30 -50 0.000 90.000 ] name "tractorRobot" color "orange")
BinRobot( pose [ -5 -40 0.000 0.000 ] name "bin1" color "blue")
BinRobot( pose [ -0 -40 0.000 0.000 ] name "bin2" color "blue")
BinRobot( pose [ 5 -40 0.000 0.000 ] name "bin3" color "blue")
