# This is the default list of robots to throw in.
AnimalRobot( pose [ 16.0 0.000 0.000 0.000 ] name "animal" color "yellow")

PersonRobot( pose [ 0.000 30.0 0.000 0.000 ] name "uneducatedPerson")
PersonRobot( pose [ -16.0 0.000 0.000 0.000 ] name "educatedPerson")

TractorRobot( pose [ -21.0 35.0 0.000 0.000 ] name "tractorRobot")

BinRobot( pose [ -4.5 -24.0 0.150 90.000 ] name "bin1")
BinRobot( pose [ -1.5 -24.0 0.150 90.000 ] name "bin2")
BinRobot( pose [ 1.5 -24.0 0.150 90.000 ] name "bin3")
BinRobot( pose [ 4.5 -24.0 0.150 90.000 ] name "bin4")

PickerRobot( pose [ -4.5 -29.0 0.000 0.000 ] name "pickerRobot1")
PickerRobot( pose [ 1.8 -29.0 0.000 0.000 ] name "pickerRobot2")
PickerRobot( pose [ 8.1 -29.0 0.000 0.000 ] name "pickerRobot3")

CarrierRobot( pose [ 31.0 -18.8 0.000 0.000 ] name "carrierRobot1")
CarrierRobot( pose [ 37.0 -26.2 0.000 0.000 ] name "carrierRobot2")
