# throw in a robot 
PickerRobot( pose [ -8.7 -37 0.000 90.000 ] name "pickerRobot" color "pink" )
MattsRobot( pose [ 16 -30 0.000 90.000 ] name "carrierRobot" color "cyan")
AnimalRobot( pose [ -15 40.000 0.000 0.000 ] name "animal" color "yellow") 
PersonRobot( pose [ -17 37.000 0.000 0.000 ] name "person" color "red" )

CarrierRobot( pose [ 15 -20 0.000 90.000 ] name "carrierRobot" color "cyan")
