# This is the default list of robots to throw in.
AnimalRobot( pose [ 20.5 0.000 0.000 0.000 ] name "animal" color "yellow")

PersonRobot( pose [ 0.000 45.0 0.000 0.000 ] name "uneducatedPerson")
PersonRobot( pose [ -20.5 0.000 0.000 0.000 ] name "educatedPerson")

TractorRobot( pose [ -25.5 50.0 0.000 0.000 ] name "tractorRobot")

BinRobot( pose [ -8.8 -39.0 0.150 90.000 ] name "bin1")
BinRobot( pose [ -5.2 -39.0 0.150 90.000 ] name "bin2")
BinRobot( pose [ -1.8 -39.0 0.150 90.000 ] name "bin3")
BinRobot( pose [ 1.8 -39.0 0.150 90.000 ] name "bin4")

PickerRobot( pose [ -8.8 -44.0 0.000 0.000 ] name "pickerRobot1")
PickerRobot( pose [ -1.4 -44.0 0.000 0.000 ] name "pickerRobot2")
PickerRobot( pose [ 5.9 -44.0 0.000 0.000 ] name "pickerRobot3")

CarrierRobot( pose [ 35.5 -25.0 0.000 0.000 ] name "carrierRobot1")
CarrierRobot( pose [ 41.5 -35.0 0.000 0.000 ] name "carrierRobot2")
