# This is the default list of robots to throw in.
AnimalRobot( pose [ 22.0 0.000 0.000 0.000 ] name "animal" color "yellow")

PersonRobot( pose [ 0.000 20.5 0.000 0.000 ] name "uneducatedPerson")
PersonRobot( pose [ -22.0 0.000 0.000 0.000 ] name "educatedPerson")

TractorRobot( pose [ -27.0 25.5 0.000 0.000 ] name "tractorRobot")

BinRobot( pose [ -8.0 -14.5 0.150 90.000 ] name "bin1")
BinRobot( pose [ 0.0 -14.5 0.150 90.000 ] name "bin2")
BinRobot( pose [ 8.0 -14.5 0.150 90.000 ] name "bin3")
BinRobot( pose [ 16.0 -14.5 0.150 90.000 ] name "bin4")

PickerRobot( pose [ -8.0 -19.5 0.000 0.000 ] name "pickerRobot1")
PickerRobot( pose [ 8.8 -19.5 0.000 0.000 ] name "pickerRobot2")
PickerRobot( pose [ 25.6 -19.5 0.000 0.000 ] name "pickerRobot3")

CarrierRobot( pose [ 37.0 -14.8 0.000 0.000 ] name "carrierRobot1")
CarrierRobot( pose [ 43.0 -20.7 0.000 0.000 ] name "carrierRobot2")
