from robot import *
from animal import *
from bin import *
from different_robot import *
from person import *
from educated_person import *
from carrier_robot import *
from picker_robot import *
from tractor import *
